/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutomatoUI;

import Principal.UIPrincipal;
import automatos.No;
import automatos.Resolve;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.geom.Point2D;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class Tela extends javax.swing.JFrame {

    private Automato grafo;
    private Vertice vertice;
    private Aresta aresta;
    private ViewPanel view;
    private ViewPanel view2;
    private ViewPanel view3;

    private No cam;
    private No camAux;
    private int camCount;
    private boolean gr;

    private int op; // 0 - novo estado, 1 -  nova transição, 2 - remover, 3 - arrastar

    /**
     * Creates new form Tela
     */
    public Tela() {
        grafo = new Automato();
        this.gr = false;
        this.view = new ViewPanel(grafo);
        this.view.setBackground(Color.white);
        this.view2 = new ViewPanel(grafo);
        this.view2.setBackground(Color.white);
        this.view3 = new ViewPanel(grafo);
        this.view3.setBackground(Color.white);
        initComponents();
        this.view.add(this.TFletra);
        this.CharTF.setEditable(false);

        this.TFletra.setSize(35, 20);
        this.TFletra.setBackground(Color.LIGHT_GRAY);
        this.TFletra.setVisible(false);


        this.op = 0; //começa com novo estado


        this.view.setBackground(Color.white);
        this.TelaPanel.add(this.TFletra);
        this.TFletra.setText("");
        this.TelaPanel.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        this.TelaPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    }

    public Tela(Automato a) {
        this.gr = true;
        this.grafo = a;
        this.view = new ViewPanel(grafo);
        this.view.setBackground(Color.white);
        this.view2 = new ViewPanel(grafo);
        this.view2.setBackground(Color.white);
        this.view3 = new ViewPanel(grafo);
        this.view3.setBackground(Color.white);
        initComponents();
        this.view.add(this.TFletra);
        this.CharTF.setEditable(false);

        this.TFletra.setSize(35, 20);
        this.TFletra.setBackground(Color.LIGHT_GRAY);
        this.TFletra.setVisible(false);

        this.op = 0; // começa com novo estado


        this.view.setBackground(Color.white);
        this.TelaPanel.add(this.TFletra);
        this.TFletra.setText("");
        this.TelaPanel.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        this.TelaPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JPopupMenu();
        PopUpItem1 = new javax.swing.JCheckBoxMenuItem();
        PopUpItem2 = new javax.swing.JCheckBoxMenuItem();
        CriarLabel_PopUpItem3 = new javax.swing.JMenuItem();
        AutomatoLayout = new javax.swing.JPanel();
        PanelAutomato = new javax.swing.JPanel();
        TelaPanel = new javax.swing.JScrollPane(this.view);
        jPanel1 = new javax.swing.JPanel();
        novoEstadoButton = new javax.swing.JButton();
        novaTransButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        arrastarButton = new javax.swing.JButton();
        TFletra = new javax.swing.JTextField();
        PanelStep = new javax.swing.JPanel();
        StepPanel = new javax.swing.JScrollPane(this.view2);
        jPanel4 = new javax.swing.JPanel();
        StepBtn = new javax.swing.JButton();
        ExitStepBtn = new javax.swing.JButton();
        StringLabel = new javax.swing.JLabel();
        CharLabel = new javax.swing.JLabel();
        CharTF = new javax.swing.JTextField();
        StringInfoLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        PanelMultEntradas = new javax.swing.JPanel();
        TablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MultEntradaTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        MultScrollPane1 = new javax.swing.JScrollPane(this.view3);
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        mi_Exe1 = new javax.swing.JMenuItem();
        mi_ExeStep = new javax.swing.JMenuItem();
        mi_MultEntradas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        PopUpItem1.setText("Inicial");
        PopUpItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopUpItem1ActionPerformed(evt);
            }
        });
        Menu.add(PopUpItem1);

        PopUpItem2.setText("Final");
        PopUpItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopUpItem2ActionPerformed(evt);
            }
        });
        Menu.add(PopUpItem2);

        CriarLabel_PopUpItem3.setLabel("Criar Label");
        CriarLabel_PopUpItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarLabel_PopUpItem3ActionPerformed(evt);
            }
        });
        Menu.add(CriarLabel_PopUpItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        AutomatoLayout.setLayout(new java.awt.CardLayout());

        TelaPanel.setBackground(new java.awt.Color(204, 204, 204));
        TelaPanel.setAutoscrolls(true);
        TelaPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        TelaPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TelaPanelMouseDragged(evt);
            }
        });
        TelaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelaPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaPanelMouseReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        novoEstadoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstadoB.png"))); // NOI18N
        novoEstadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEstadoButtonActionPerformed(evt);
            }
        });

        novaTransButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/transicaoB.png"))); // NOI18N
        novaTransButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaTransButtonActionPerformed(evt);
            }
        });

        removerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DeleteB.png"))); // NOI18N
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        arrastarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cursorB.png"))); // NOI18N
        arrastarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrastarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novoEstadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novaTransButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(arrastarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(novoEstadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novaTransButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arrastarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        TFletra.setText("jTextField1");
        TFletra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFletraFocusLost(evt);
            }
        });
        TFletra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFletraKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelAutomatoLayout = new javax.swing.GroupLayout(PanelAutomato);
        PanelAutomato.setLayout(PanelAutomatoLayout);
        PanelAutomatoLayout.setHorizontalGroup(
            PanelAutomatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAutomatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAutomatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelAutomatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAutomatoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TFletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelAutomatoLayout.setVerticalGroup(
            PanelAutomatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAutomatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(TelaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelAutomatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAutomatoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TFletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        AutomatoLayout.add(PanelAutomato, "AutomatoEdit");

        StepBtn.setText("Começar");
        StepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepBtnActionPerformed(evt);
            }
        });

        ExitStepBtn.setText("Sair");
        ExitStepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitStepBtnActionPerformed(evt);
            }
        });

        CharLabel.setText("Character aceito:");

        StringInfoLabel.setText("String:");

        resultLabel.setText("--");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StepBtn)
                .addGap(18, 18, 18)
                .addComponent(ExitStepBtn)
                .addGap(94, 94, 94)
                .addComponent(StringLabel)
                .addGap(59, 59, 59)
                .addComponent(CharLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CharTF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StringInfoLabel)
                    .addComponent(resultLabel))
                .addGap(84, 84, 84))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StepBtn)
                    .addComponent(ExitStepBtn)
                    .addComponent(StringLabel))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CharLabel)
                    .addComponent(CharTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StringInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultLabel))
        );

        javax.swing.GroupLayout PanelStepLayout = new javax.swing.GroupLayout(PanelStep);
        PanelStep.setLayout(PanelStepLayout);
        PanelStepLayout.setHorizontalGroup(
            PanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StepPanel)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelStepLayout.setVerticalGroup(
            PanelStepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AutomatoLayout.add(PanelStep, "AutomatoStep");

        MultEntradaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Entrada", "Resultado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        MultEntradaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(MultEntradaTable);
        if (MultEntradaTable.getColumnModel().getColumnCount() > 0) {
            MultEntradaTable.getColumnModel().getColumn(0).setResizable(false);
            MultEntradaTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Inserir Linha");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        MultScrollPane1.setAutoscrolls(true);
        MultScrollPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MultScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(MultScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelMultEntradasLayout = new javax.swing.GroupLayout(PanelMultEntradas);
        PanelMultEntradas.setLayout(PanelMultEntradasLayout);
        PanelMultEntradasLayout.setHorizontalGroup(
            PanelMultEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMultEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelMultEntradasLayout.setVerticalGroup(
            PanelMultEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMultEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        AutomatoLayout.add(PanelMultEntradas, "AutomatoMult");

        Menu1.setText("Executar");

        mi_Exe1.setText("Uma entrada");
        mi_Exe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_Exe1ActionPerformed(evt);
            }
        });
        Menu1.add(mi_Exe1);

        mi_ExeStep.setText("Passo a passo");
        mi_ExeStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ExeStepActionPerformed(evt);
            }
        });
        Menu1.add(mi_ExeStep);

        mi_MultEntradas.setText("Multiplas Entradas");
        mi_MultEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_MultEntradasActionPerformed(evt);
            }
        });
        Menu1.add(mi_MultEntradas);

        jMenuBar1.add(Menu1);

        jMenu1.setText("Conversão");

        jMenuItem1.setText("Gramatica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Expressão Regular");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("AFD");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Remover Transições Vazias");

        jMenuItem4.setText("Remover");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AutomatoLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AutomatoLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFletraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFletraKeyPressed
        if (evt.getKeyChar() == '\n') {
            this.TFletra.setVisible(false);
        }
    }//GEN-LAST:event_TFletraKeyPressed

    private void TFletraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFletraFocusLost
        String aux1 = this.TFletra.getText();
        aux1 = aux1.trim();
        Character aux;

        if (aux1.equals("")) {
            aux = '\u03bb';
        } else {
            if (aux1.length() > 1) {
                JOptionPane.showMessageDialog(this, "Apenas o primeiro caracter será foi registrado");
            }
            aux = aux1.charAt(0);
        }
        this.TFletra.setText("");

        this.aresta.addEstado(aux);
        this.TelaPanel.repaint();
    }//GEN-LAST:event_TFletraFocusLost

    private void TelaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMouseReleased
        try {
            this.view.getS().setLine(0, 0, 0, 0);
            Point p = this.view.getMousePosition();
            Vertice v = grafo.busca(p.x, p.y);

            if (evt.isPopupTrigger()) {
                if (this.vertice == null) {
                    this.PopUpItem1.setEnabled(false);
                    this.PopUpItem2.setEnabled(false);
                } else {

                    this.PopUpItem1.setSelected(this.vertice.isInicial());
                    this.PopUpItem2.setSelected(this.vertice.isFim());
                    this.PopUpItem1.setEnabled(true);
                    this.PopUpItem2.setEnabled(true);
                }
                this.Menu.show(this.view, p.x, p.y);
                return;
            }
            if (this.op == 1) {//transição
                if (v == null) {
                    return;
                }
                int aux;
                this.aresta = this.grafo.addAresta(this.vertice, v);
                if (this.aresta.getTipo() == 4) {
                    this.TFletra.setLocation(this.vertice.getX() - 25, this.vertice.getY() + 25);
                } else {
                    this.TFletra.setLocation((this.vertice.getX() + p.x) / 2, (this.vertice.getY() + p.y) / 2 - 10);
                }
                this.TFletra.setVisible(true);
                this.TFletra.requestFocus();

            }

        } catch (NullPointerException e) {

        } finally {
            this.view.updateUI();
        }
    }//GEN-LAST:event_TelaPanelMouseReleased

    private void TelaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMousePressed
        try {
            if (vertice != null) {
                this.vertice.setFocus(false);
            }
            Point p = this.view.getMousePosition();
            this.vertice = grafo.busca(p.x, p.y);
            if (vertice != null) {
                this.vertice.setFocus(true);
            }
            if (this.TFletra.isVisible()) {
                Point pAux = this.TFletra.getLocation();
                if ((p.x - pAux.x) > 50 || (p.y - pAux.y) > 20) {
                    this.TFletra.setVisible(false);
                }
            }
            this.TelaPanel.repaint();
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_TelaPanelMousePressed

    private void TelaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMouseClicked
        Point p = this.view.getMousePosition();
        if (this.op == 0) {//novo estado
            if (this.vertice != null) {
                return;
            }
            this.vertice = new Vertice(p.x, p.y, "q");
            this.grafo.addVertice(this.vertice);

        }
        if (this.op == 2) {//remove
            if (this.vertice != null) {
                if (this.vertice.isInicial()) {
                    this.grafo.setInicial(null);
                }
                this.grafo.removeVertice(this.vertice);
            } else {
                this.grafo.removeTransicao(p);
            }
        }
        this.view.repaint();
    }//GEN-LAST:event_TelaPanelMouseClicked

    private void TelaPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMouseDragged
        try {
            if (this.op == 3) {//arrastar

                Point p = this.view.getMousePosition();

                if (this.vertice != null) {
                    this.vertice.setX(p.x);
                    this.vertice.setY(p.y);
                }

            } else if (this.vertice != null && this.op == 1) {//transição
                Point2D p = (Point2D) this.view.getMousePosition();
                this.view.getS().setLine(p.getX(), p.getY(), vertice.getX(), vertice.getY());
            }

        } catch (NullPointerException e) {

        } finally {
            this.view.updateUI();
        }
    }//GEN-LAST:event_TelaPanelMouseDragged

    private void PopUpItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpItem1ActionPerformed
        if (this.grafo.getInicial() != null) {
            this.grafo.getInicial().setInicial(false);
        }
        this.vertice.setInicial(true);
        this.grafo.setInicial(this.vertice);
        this.TelaPanel.repaint();
    }//GEN-LAST:event_PopUpItem1ActionPerformed

    private void PopUpItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpItem2ActionPerformed
        this.vertice.setFim(!this.vertice.isFim());
        this.TelaPanel.repaint();
    }//GEN-LAST:event_PopUpItem2ActionPerformed

    private void mi_Exe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_Exe1ActionPerformed
        this.grafo.setPos();

        if (this.grafo.getInicial() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado inicial");
            return;
        }
        Resolve r = new Resolve(this.grafo);
        String aux = JOptionPane.showInputDialog(this, "Insira uma entrada");
        if (r.busca(aux)) {
            JOptionPane.showMessageDialog(this, "Aceito");
        } else {
            JOptionPane.showMessageDialog(this, "Rejeitado");
        }
    }//GEN-LAST:event_mi_Exe1ActionPerformed

    private void mi_ExeStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ExeStepActionPerformed
        this.grafo.setPos();
        this.CharTF.setText("");
        this.resultLabel.setText("");

        if (this.grafo.getInicial() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado inicial");
            return;
        }
        Resolve r = new Resolve(this.grafo);
        String aux = JOptionPane.showInputDialog(this, "Insira uma entrada");
        if (r.busca(aux)) {
            if (vertice != null) {
                this.vertice.setFocus(false);
            }
            this.camCount = 0;
            this.cam = r.getCaminnho();
            this.camAux = this.cam;
            this.StepPanel.repaint();
            CardLayout card = (CardLayout) this.AutomatoLayout.getLayout();
            card.show(this.AutomatoLayout, "AutomatoStep");
        } else {
            JOptionPane.showMessageDialog(this, "Entrada rejeitada");
        }
    }//GEN-LAST:event_mi_ExeStepActionPerformed

    private void StepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepBtnActionPerformed
        if (this.camCount == 2) {
            this.camCount = 0;
            this.StepBtn.setText("Começar");
            this.vertice.setFocus(false);
            this.CharTF.setText("");
            this.resultLabel.setText("");
        } else {

            if (this.camCount != 1) {
                this.camCount = 1;
                this.StepBtn.setText("Próximo");
            }
            if (this.vertice != null) {
                this.vertice.setFocus(false);
            }
            if (!camAux.getTransicao().isEmpty()) {
                String aux = camAux.getTransicao().get(0).toString();
                this.CharTF.setText(aux);
                if (!aux.equals("" + '\u03bb')) {
                    this.resultLabel.setText(this.resultLabel.getText() + aux);
                }
            }
            this.vertice = this.grafo.setSelected(this.camAux.getEstado());
            if (this.camAux.getProx() != null) {
                this.camAux = this.camAux.getProx();
            } else {
                this.camCount = 2;
                this.camAux = this.cam;
                this.StepBtn.setText("Recomeçar");

            }
        }
        this.StepPanel.repaint();
    }//GEN-LAST:event_StepBtnActionPerformed

    private void ExitStepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitStepBtnActionPerformed
        CardLayout card = (CardLayout) this.AutomatoLayout.getLayout();
        card.show(this.AutomatoLayout, "AutomatoEdit");
    }//GEN-LAST:event_ExitStepBtnActionPerformed

    private void mi_MultEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_MultEntradasActionPerformed
        this.MultScrollPane1.repaint();
        CardLayout card = (CardLayout) this.AutomatoLayout.getLayout();
        card.show(this.AutomatoLayout, "AutomatoMult");
    }//GEN-LAST:event_mi_MultEntradasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout card = (CardLayout) this.AutomatoLayout.getLayout();
        card.show(this.AutomatoLayout, "AutomatoEdit");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = this.MultEntradaTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) this.MultEntradaTable.getModel();
        this.grafo.setPos();
        this.MultEntradaTable.getCellEditor().stopCellEditing();
        if (this.grafo.getInicial() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado inicial");
            return;
        }
        Resolve r = new Resolve(this.grafo);
        for (int j = 0; j < i; j++) {
            String aux = (String) model.getValueAt(j, 0);
            if (aux != null) {
                if (r.busca(aux)) {
                    model.setValueAt("Aceito", j, 1);
                } else {
                    model.setValueAt("Rejeitado", j, 1);
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) this.MultEntradaTable.getModel();
        model.addRow(new Object[2]);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!this.gr) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new UIPrincipal().setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.grafo.setPos();

        if (this.grafo.getInicial() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado inicial");
            return;
        }
        Resolve r = new Resolve(this.grafo);

        JOptionPane.showMessageDialog(this, r.AF2GR());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.grafo.setPos();

        if (this.grafo.getInicial() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado inicial");
            return;
        }
        Resolve r = new Resolve(this.grafo);

        JOptionPane.showMessageDialog(this, r.AF2ER());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.grafo.setPos();

        if (this.grafo.getInicial() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um Estado inicial");
            return;
        }
        this.grafo.afnd2afd();
        this.TelaPanel.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.grafo.removeVazio();
        this.TelaPanel.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
  

    private void novoEstadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEstadoButtonActionPerformed
        this.op = 0;
    }//GEN-LAST:event_novoEstadoButtonActionPerformed

    private void novaTransButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaTransButtonActionPerformed
        this.op = 1;
    }//GEN-LAST:event_novaTransButtonActionPerformed

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        this.op = 2;
    }//GEN-LAST:event_removerButtonActionPerformed

    private void arrastarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrastarButtonActionPerformed
        this.op = 3;
    }//GEN-LAST:event_arrastarButtonActionPerformed

    private void CriarLabel_PopUpItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarLabel_PopUpItem3ActionPerformed
        // TODO add your handling code here:
        String label = JOptionPane.showInputDialog("Insira o label!");
        this.grafo.criarLabel(label, this.vertice);
        this.TelaPanel.repaint();
    }//GEN-LAST:event_CriarLabel_PopUpItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });

    }

    public class MeuPanel extends javax.swing.JPanel {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutomatoLayout;
    private javax.swing.JLabel CharLabel;
    private javax.swing.JTextField CharTF;
    private javax.swing.JMenuItem CriarLabel_PopUpItem3;
    private javax.swing.JButton ExitStepBtn;
    private javax.swing.JPopupMenu Menu;
    private javax.swing.JMenu Menu1;
    private javax.swing.JTable MultEntradaTable;
    private javax.swing.JScrollPane MultScrollPane1;
    private javax.swing.JPanel PanelAutomato;
    private javax.swing.JPanel PanelMultEntradas;
    private javax.swing.JPanel PanelStep;
    private javax.swing.JCheckBoxMenuItem PopUpItem1;
    private javax.swing.JCheckBoxMenuItem PopUpItem2;
    private javax.swing.JButton StepBtn;
    private javax.swing.JScrollPane StepPanel;
    private javax.swing.JLabel StringInfoLabel;
    private javax.swing.JLabel StringLabel;
    private javax.swing.JTextField TFletra;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JScrollPane TelaPanel;
    private javax.swing.JButton arrastarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mi_Exe1;
    private javax.swing.JMenuItem mi_ExeStep;
    private javax.swing.JMenuItem mi_MultEntradas;
    private javax.swing.JButton novaTransButton;
    private javax.swing.JButton novoEstadoButton;
    private javax.swing.JButton removerButton;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
