/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GramaticaUI;

import AutomatoUI.Automato;
import AutomatoUI.Tela;
import Gramatica.Gramatica;
import Principal.UIPrincipal;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.CellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diovanni
 */
public class UIGramatica extends javax.swing.JFrame {

    private Gramatica g;
    private int op;

    /**
     * Creates new form UIGramática
     */
    public UIGramatica() {
        initComponents();
        CardLayout card = (CardLayout) this.jPanelLayout.getLayout();
        card.show(jPanelLayout, "cardGeral");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLayout = new javax.swing.JPanel();
        jPanelGeral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonMult = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonAddLinha = new javax.swing.JButton();
        jButtonExcLinhas = new javax.swing.JButton();
        jButtonInput = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGram = new javax.swing.JTable();
        multEntrada = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MultEntradaTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanelLayout.setLayout(new java.awt.CardLayout());

        jButtonMult.setText("Múltiplas Entradas");
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });

        jButtonClear.setText("Limpar Tudo");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonAddLinha.setText("Adicionar Linha");
        jButtonAddLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLinhaActionPerformed(evt);
            }
        });

        jButtonExcLinhas.setText("Excluir Linha");
        jButtonExcLinhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcLinhasActionPerformed(evt);
            }
        });

        jButtonInput.setText("Única Entrada");
        jButtonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputActionPerformed(evt);
            }
        });

        jButton1.setText("Converter para AF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddLinha)
                    .addComponent(jButtonInput))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonExcLinhas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMult)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAddLinha)
                    .addComponent(jButtonExcLinhas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMult)
                    .addComponent(jButtonInput)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTableGram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null}
            },
            new String [] {
                "Não-Terminal", "", "Definição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGram.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableGram.getTableHeader().setReorderingAllowed(false);
        jTableGram.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableGramComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGram);

        javax.swing.GroupLayout jPanelGeralLayout = new javax.swing.GroupLayout(jPanelGeral);
        jPanelGeral.setLayout(jPanelGeralLayout);
        jPanelGeralLayout.setHorizontalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanelGeralLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelGeralLayout.setVerticalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanelLayout.add(jPanelGeral, "cardGeral");

        MultEntradaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Entrada", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(MultEntradaTable);

        jButton4.setText("Adicionar Linha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Executar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Remover Linha");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Sair");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7)))
        );

        javax.swing.GroupLayout multEntradaLayout = new javax.swing.GroupLayout(multEntrada);
        multEntrada.setLayout(multEntradaLayout);
        multEntradaLayout.setHorizontalGroup(
            multEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multEntradaLayout.createSequentialGroup()
                .addGroup(multEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        multEntradaLayout.setVerticalGroup(
            multEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multEntradaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelLayout.add(multEntrada, "cardMult");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputActionPerformed
        CellEditor ce = this.jTableGram.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }
        Gramatica g = this.verificaEntrada();
        if (g == null) {
            return;
        }
        String str = JOptionPane.showInputDialog(rootPane, "Insira uma Entrada:");
        if (str == null) {
            return;
        }

        if (g.busca(str)) {
            JOptionPane.showMessageDialog(this, "Aceito");
        } else {
            JOptionPane.showMessageDialog(this, "Rejeitado");
        }

    }//GEN-LAST:event_jButtonInputActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        CellEditor ce = this.jTableGram.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }
        this.g = this.verificaEntrada();
        if (g != null) {
            CardLayout card = (CardLayout) this.jPanelLayout.getLayout();
            card.show(jPanelLayout, "cardMult");
        }
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }//GEN-LAST:event_formWindowClosed

    private void jTableGramComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableGramComponentAdded
        this.jTableGram.getModel().setValueAt("➜", this.jTableGram.getSelectedRow(), 1);
    }//GEN-LAST:event_jTableGramComponentAdded

    private void jButtonAddLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLinhaActionPerformed
        CellEditor ce = this.jTableGram.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }

        DefaultTableModel model;
        model = (DefaultTableModel) this.jTableGram.getModel();
        model.addRow(new Object[3]);

    }//GEN-LAST:event_jButtonAddLinhaActionPerformed

    private void jButtonExcLinhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcLinhasActionPerformed
        CellEditor ce = this.jTableGram.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }

        DefaultTableModel model;
        model = (DefaultTableModel) this.jTableGram.getModel();

        if (this.jTableGram.getModel().getRowCount() == 1) {
            return;
        } else {
            model.removeRow(this.jTableGram.getModel().getRowCount() - 1);
        }
    }//GEN-LAST:event_jButtonExcLinhasActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        CellEditor ce = this.jTableGram.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }

        DefaultTableModel model;
        model = (DefaultTableModel) this.jTableGram.getModel();

        model.setRowCount(1);

        this.jTableGram.getModel().setValueAt(null, 0, 0);
        this.jTableGram.getModel().setValueAt(null, 0, 2);

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int num = this.MultEntradaTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) this.MultEntradaTable.getModel();
        CellEditor ce = this.MultEntradaTable.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }
        String aux;
        for (int i = 0; i < num; i++) {
            aux = (String) this.MultEntradaTable.getValueAt(i, 0);
            if (aux != null && g.busca(aux)) {
                this.MultEntradaTable.setValueAt("Aceito", i, 1);
            } else {
                this.MultEntradaTable.setValueAt("Rejeitado", i, 1);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int num = this.MultEntradaTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) this.MultEntradaTable.getModel();

        model.setRowCount(num + 1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int num = this.MultEntradaTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) this.MultEntradaTable.getModel();

        model.setRowCount(num - 1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout card = (CardLayout) this.jPanelLayout.getLayout();
        card.show(jPanelLayout, "cardGeral");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CellEditor ce = this.jTableGram.getCellEditor();
        if (ce != null) {
            ce.stopCellEditing();
        }

        Gramatica g = this.verificaEntrada();
        if (g == null) {
            return;
        }

        Automato a = g.gr2af();

        Tela telaAutomato = new Tela(a);
        telaAutomato.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private Gramatica verificaEntrada() {
        String aux, aux2;
        int auxLenght;
        ArrayList<String> strAux = new ArrayList();
        for (int i = 0; i < this.jTableGram.getModel().getRowCount(); i++) {
            aux = (String) this.jTableGram.getModel().getValueAt(i, 0);
            aux2 = (String) this.jTableGram.getModel().getValueAt(i, 2);

            if (aux == null || aux.isEmpty()) {
                if (aux2 == null || aux2.isEmpty()) {
                    continue;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Parte NÃO-TERMINAL não pode ser vazia! Linha " + i + 1);
                    return null;
                }

            }
            if (aux.length() > 1) {
                JOptionPane.showMessageDialog(rootPane, "Parte NÃO-TERMINAL não pode conter mais de um elemento! Linha " + i + 1);
                return null;
            }

            if (aux2 == null || aux2.isEmpty()) {
                this.jTableGram.getModel().setValueAt("" + '\u03bb', i, 2);
                aux2 = "" + '\u03bb';

            }

            auxLenght = aux2.length();
            if (!Character.isUpperCase(aux.charAt(0))) {
                JOptionPane.showMessageDialog(rootPane, "Erros na sintaxe da parte NÃO-TERMINAL! Linha " + i + 1);
                return null;
            }
            if (auxLenght > 2) {
                JOptionPane.showMessageDialog(rootPane, "Gramática deve ser REGULAR! Linha " + i + 1);
                return null;
            }
            if (Character.isLowerCase(aux2.charAt(0)) || Character.isDigit(aux2.charAt(0))) {
                if (auxLenght == 2 && (!Character.isUpperCase(aux2.charAt(1)) || aux2.charAt(0) == '\u03bb')) {
                    JOptionPane.showMessageDialog(rootPane, "Gramática deve ser REGULAR UNITÁRIA A ESQUERDA! Linha " + i + 1);
                    return null;
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Gramática deve ser REGULAR UNITÁRIA A ESQUERDA! Linha " + i + 1);
                return null;
            }

            strAux.add(aux);
            strAux.add(aux2);
        }
        return new Gramatica(strAux);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIGramatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIGramatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIGramatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIGramatica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIGramatica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MultEntradaTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAddLinha;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonExcLinhas;
    private javax.swing.JButton jButtonInput;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelLayout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableGram;
    private javax.swing.JPanel multEntrada;
    // End of variables declaration//GEN-END:variables
}
