/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desenho;

import Principal.UIPrincipal;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author fabio
 */
public class Tela extends javax.swing.JFrame {

    private Automato grafo;
    private Vertice vertice;
    private Aresta aresta;
    private BufferedImage imageBuffer;
    private int next;
    private ViewPanel view;

    private Vertice Inicial;

    /**
     * Creates new form Tela
     */
    public Tela() {
        grafo = new Automato();
        this.view = new ViewPanel(grafo);
        this.view.setBackground(Color.white);
        initComponents();

        this.TFletra.setSize(35, 20);
        this.TFletra.setBackground(Color.LIGHT_GRAY);
        this.TFletra.setVisible(false);

        next = 0;
        this.newButton.setSelected(true);

        this.view.setBackground(Color.white);
        this.TelaPanel.add(this.TFletra);
        this.TFletra.setText("");
        this.TelaPanel.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        this.TelaPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Menu = new javax.swing.JPopupMenu();
        PopUpItem1 = new javax.swing.JCheckBoxMenuItem();
        PopUpItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        dragButton = new javax.swing.JRadioButton();
        newButton = new javax.swing.JRadioButton();
        RBTrans = new javax.swing.JRadioButton();
        TFletra = new javax.swing.JTextField();
        RBRemove = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        TelaPanel = new javax.swing.JScrollPane(this.view);

        PopUpItem1.setText("Inicial");
        PopUpItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopUpItem1ActionPerformed(evt);
            }
        });
        Menu.add(PopUpItem1);

        PopUpItem2.setText("Final");
        PopUpItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopUpItem2ActionPerformed(evt);
            }
        });
        Menu.add(PopUpItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonGroup1.add(dragButton);
        dragButton.setText("Arrastar");

        buttonGroup1.add(newButton);
        newButton.setText("Estado");

        buttonGroup1.add(RBTrans);
        RBTrans.setText("Transição");

        TFletra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFletraFocusLost(evt);
            }
        });
        TFletra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFletraKeyPressed(evt);
            }
        });

        buttonGroup1.add(RBRemove);
        RBRemove.setText("Remover");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TFletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBTrans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(dragButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dragButton)
                    .addComponent(newButton)
                    .addComponent(RBTrans)
                    .addComponent(RBRemove))
                .addGap(18, 18, 18)
                .addComponent(TFletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelaPanel.setBackground(new java.awt.Color(255, 51, 102));
        TelaPanel.setAutoscrolls(true);
        TelaPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TelaPanelMouseDragged(evt);
            }
        });
        TelaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelaPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TelaPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaPanel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(TelaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFletraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFletraKeyPressed
        if (evt.getKeyChar() == '\n') {
            this.TFletra.setVisible(false);

        }
    }//GEN-LAST:event_TFletraKeyPressed

    private void TFletraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFletraFocusLost
        String aux = this.TFletra.getText();
        this.TFletra.setText("");
        if (aux.equals("")) {
            aux = "\u03bb";
        }
        this.aresta.addEstado(aux);
        this.TelaPanel.repaint();
    }//GEN-LAST:event_TFletraFocusLost

    private void TelaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMouseReleased
        this.view.setS(null);
        Point p = this.TelaPanel.getMousePosition();
        Vertice v = grafo.busca(p.x, p.y);

        if (evt.isPopupTrigger()) {
            if (this.vertice == null) {
                this.PopUpItem1.setEnabled(false);
                this.PopUpItem2.setEnabled(false);
            } else {

                this.PopUpItem1.setSelected(this.vertice.isInicial());
                this.PopUpItem2.setSelected(this.vertice.isFim());
                this.PopUpItem1.setEnabled(true);
                this.PopUpItem2.setEnabled(true);
            }
            this.Menu.show(this.TelaPanel, p.x, p.y);
            return;
        }
        if (this.RBTrans.isSelected()) {
            if (v == null) {
                return;
            }
            int aux;
            this.aresta = this.grafo.addAresta(this.vertice, v);
            if (this.aresta.getTipo() == 4) {
                this.TFletra.setLocation(this.vertice.getX() - 25, this.vertice.getY() + 25);
            } else {
                this.TFletra.setLocation((this.vertice.getX() + p.x) / 2, (this.vertice.getY() + p.y) / 2 - 10);
            }
            this.TFletra.setVisible(true);
            this.TFletra.requestFocus();

        }

        this.view.repaint();
    }//GEN-LAST:event_TelaPanelMouseReleased

    private void TelaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMousePressed
        if (vertice != null) {
            this.vertice.setFocus(false);
        }
        Point p = this.TelaPanel.getMousePosition();
        this.vertice = grafo.busca(p.x, p.y);
        if (vertice != null) {
            this.vertice.setFocus(true);
        }
        if (this.TFletra.isVisible()) {
            Point pAux = this.TFletra.getLocation();
            if ((p.x - pAux.x) > 50 || (p.y - pAux.y) > 20) {
                this.TFletra.setVisible(false);
            }
        }
        this.TelaPanel.repaint();
    }//GEN-LAST:event_TelaPanelMousePressed

    private void TelaPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMouseClicked
        Point p = this.TelaPanel.getMousePosition();
        if (this.newButton.isSelected()) {
            if (this.vertice != null) {
                return;
            }
            this.vertice = new Vertice(p.x, p.y, "q" + next++);
            this.grafo.addVertice(this.vertice);

        }
        if (this.RBRemove.isSelected()) {
            if (this.vertice != null) {
                if (this.vertice.isInicial()) {
                    this.Inicial = null;
                }
                this.grafo.removeVertice(this.vertice);
            } else {
                this.grafo.removeTransicao(p);
            }
        }
        this.view.repaint();
    }//GEN-LAST:event_TelaPanelMouseClicked

    private void TelaPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaPanelMouseDragged

        if (this.dragButton.isSelected()) {
            Point p = this.view.getMousePosition();

            if (this.vertice != null) {
                this.vertice.setX(p.x);
                this.vertice.setY(p.y);
            }

        } else if (this.vertice != null && this.RBTrans.isSelected()) {
            Point p = this.view.getMousePosition();
            this.view.setS(new Line2D.Float(new Point(vertice.getX(), vertice.getY()), p));
        }

        this.view.repaint();
    }//GEN-LAST:event_TelaPanelMouseDragged

    private void PopUpItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpItem1ActionPerformed
        if (this.Inicial != null) {
            this.Inicial.setInicial(false);
        }
        this.vertice.setInicial(true);
        this.Inicial = this.vertice;
        this.TelaPanel.repaint();
    }//GEN-LAST:event_PopUpItem1ActionPerformed

    private void PopUpItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopUpItem2ActionPerformed
        this.vertice.setFim(!this.vertice.isFim());
        this.TelaPanel.repaint();
    }//GEN-LAST:event_PopUpItem2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    public class MeuPanel extends javax.swing.JPanel {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Menu;
    private javax.swing.JCheckBoxMenuItem PopUpItem1;
    private javax.swing.JCheckBoxMenuItem PopUpItem2;
    private javax.swing.JRadioButton RBRemove;
    private javax.swing.JRadioButton RBTrans;
    private javax.swing.JTextField TFletra;
    private javax.swing.JScrollPane TelaPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dragButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton newButton;
    // End of variables declaration//GEN-END:variables
}
